services:
  alerts:
    path: src/services/alerts
  connector:
    path: src/services/connector
    params:
    ecsFailureTopicArn: ${alerts.ECSFailureTopicArn}
  ksqldb:
    path: src/services/ksqldb
    params:
      ecsFailureTopicArn: ${alerts.ECSFailureTopicArn}
  dashboard:
    path: src/services/dashboard
